spring:
    application:
        name: wbkdng-discovery

server:
    port: 9001

eureka:
    instance:
        hostname: localhost
        prefer-ip-address: true
    client:
        register-with-eureka: false
        fetch-registry: false
        serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


management: 
  endpoints:
    enabled-by-default: true
    web: 
      exposure: 
        include: info, health

info:
    app:
        name: ${spring.application.name}
        version: "1.0.0"